version: '3.9'


services:

  backend:
    container_name: resume_django
    build: .
    expose:
      - '8003'
    env_file:
      - ./.env
      - ./db.env
    volumes:
      - ./backend:/app
      - resume-static-volume:/app/static_files
    command: sh ./deploy_command.sh

  nginx:
    container_name: resume_nginx
    image: nginx
    ports:
      - '83:80'
    restart: always
    depends_on:
      - backend
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - resume-media-volume:/home/app/media
      - resume-static-volume:/home/app/static

  psql:
    container_name: resume_psql
    image: postgres:15-alpine3.18
    env_file:
      - ./db.env
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./secret.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - 5432:5432
volumes:
  resume-media-volume:
  resume-static-volume: