# Generated by Django 4.2.2 on 2023-06-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=248)),
                ('github_link', models.CharField(blank=True, max_length=120, null=True)),
                ('project_link', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.TextField()),
                ('status', models.SmallIntegerField(choices=[(0, 'developing'), (1, 'improving'), (2, 'finished')])),
                ('tags', models.ManyToManyField(to='projects.tags')),
            ],
        ),
    ]
