# Generated by Django 4.2.2 on 2023-06-28 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_skills_alter_tag_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='skills',
            new_name='technologies',
        ),
    ]
