# Generated by Django 4.2.2 on 2023-06-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='certificate or course name')),
                ('certificate_source', models.CharField(max_length=256)),
                ('course_main_master', models.CharField(blank=True, max_length=256, null=True)),
                ('score', models.CharField(blank=True, max_length=128, null=True)),
                ('image', models.ImageField(upload_to='certificates/')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.SmallIntegerField(choices=[(0, 'fa'), (1, 'en')], default=0)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('tag', models.SmallIntegerField(choices=[(0, 'django'), (1, 'frontend'), (2, 'linux'), (3, 'node'), (4, 'others')])),
                ('tier', models.SmallIntegerField(choices=[(0, 'familiar'), (1, 'medium'), (2, 'highlighted')])),
                ('details', models.CharField(blank=True, max_length=248, null=True)),
            ],
        ),
    ]
