# Generated by Django 4.2.2 on 2023-06-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.SmallIntegerField(choices=[(0, "fa"), (1, "en")], default=0),
                ),
                ("body", models.TextField()),
            ],
        ),
    ]
