# Generated by Django 4.2.2 on 2023-06-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0002_resume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="details",
            field=models.CharField(blank=True, max_length=248, null=True),
        ),
    ]
