# Generated by Django 4.2.2 on 2023-06-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_skill_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='certificate or course name')),
                ('certificate_source', models.CharField(max_length=256)),
                ('course_main_master', models.CharField(blank=True, max_length=256, null=True)),
                ('score', models.CharField(blank=True, max_length=128, null=True)),
                ('image', models.ImageField(upload_to='certificates/')),
            ],
        ),
    ]
